"use client";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";

import "./globals.css";
import Header from "./header/header";
import Footer from "./footer/page";
import { createContext, useEffect, useReducer, useState } from "react";
import { usePathname } from "next/navigation";
import { boolean } from "yup";
const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

interface LoginStatusContextType {
  loggedIn: boolean;
  setLoggedIn: React.Dispatch<React.SetStateAction<boolean>>;
}

const defaultLoginStatus: LoginStatusContextType = {
  loggedIn: false,
  setLoggedIn: () => {},
};

export const LoginStatusContext =
  createContext<LoginStatusContextType>(defaultLoginStatus);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [loggedIn, setLoggedIn] = useState(false);

  useEffect(() => {
    if (localStorage.getItem("loggedIn") === "true") setLoggedIn(true);
  }, []);
  return (
    <>
      <html lang="en">
        <title>patrolman App</title>
        <body className={inter.className}>
          <LoginStatusContext.Provider value={{ loggedIn, setLoggedIn }}>
            <Header />
            <div>{children}</div>
            <Footer />
          </LoginStatusContext.Provider>
        </body>
      </html>
    </>
  );
}
